/* 데이터베이스 생성 */
CREATE DATABASE FG_DB DEFAULT CHARACTER SET UTF8;
/* 관리자 생성 */
CREATE USER FG_ADMIN@'%' IDENTIFIED BY 'FG_ADMIN!';
/* 관리자 권한부여 */
GRANT ALL PRIVILEGES ON FG_DB.* TO 'FG_ADMIN'@'%';

SHOW DATABASES;
USE FG_DB;
SHOW TABLES;
